[workspace]
resolver = "2"
members = ["audio", "node", "bot"]

[workspace.dependencies]
songbird = { version = "0.6", default-features = false }
symphonia = { version = "0.5", features = [
    "aac",
    "alac",
    "flac",
    "isomp4",
    "mkv",
    "mp3",
    "ogg",
    "pcm",
    "vorbis",
    "wav",
] }
tokio = { version = "1" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"

[profile.release]
lto = true
codegen-units = 1
